### ISSUE TITLE
`ToggleCam` Service

### ISSUE THREAD

**Issue by sytang** [AutonomyLab/ardrone_autonomy#15]
Hi! First of all, thank you for taking the time to create such a helpful package, I''m finding it very useful for my senior thesis project. One point of clarification - the instructions say to call the togglecam service with an empty message. There's additionally a CamSelect.srv service messages as well. What is the difference between the two? Thank you!

**Comment by parcon** [comment]
I'm very interested in this as well! How do you call that service? Is it a ROS message?
EDIT: Nevermind, to call the service you use 

``` bash
$rosservice call /ardrone/togglecam
```

**Comment by mani-monaj** [comment]
> Hi! First of all, thank you for taking the time to create such a helpful package, I''m finding it very useful for my senior thesis project. One point of clarification - the instructions say to call the togglecam service with an empty message. There's additionally a CamSelect.srv service messages as well. What is the difference between the two? Thank you! 

The `CamSelect.srv` has not been implemented yet and should be removed because it basically does the same thing as `togglecam` service. As @parcon mentioned, the correct way to toggle the cam is `rosservice call /ardrone/togglecam`. This is also possible to call this service using `rosservice` API for C++ or Python.
