### ISSUE TITLE
imu_calibration

### ISSUE THREAD

**Issue by devagl** [AutonomyLab/ardrone_autonomy#21]
So according to this paper, (http://cas.ensmp.fr/~petit/papers/ifac11/PJB.pdf) the navdata velocity estimates are based on fused estimates from the optical flow and the aerodynamic model of the drone. When an estimate is unavailable from the bottom camera, simply the aerodynamic model is used. 

This means the biases are recalculated automatically as and when the estimate switches from a fused one to the aerodynamic one. So, does it make sense for you to still do your recalibration in the beginning and stick with that value through a given run of the drone? Wouldn't that already be done much better on the embedded system?

**Comment by mani-monaj** [comment]
That is a very interesting point. The IMU calibration (as stated in docs) is experimental. I added that to the driver, because the sensor fusion module that I used for a project was working better when the biases are reduced (even using this naive method). I need to do some experiments (after applying #18) to see if it actually works in long term. I would also really appreciate your (and other people's) opinions.

**Comment by devagl** [comment]
I actually came across this because I noticed that the reduced bias actually tends to 'stick' through the experiment, which means it doesn't help much! I created a bag file that recorded data from /navdata and /cmd_vel topic, and both graphs look similar albeit with a time lag in the /navdata topic. Since there is an inherent filter in the embedded system, and optical flow is the more significant contributor to the velocity estimate, it doesn't make sense to filter it in my opinion!

Was your project on the drone too?
