### ISSUE TITLE
Receiving GPS data

### ISSUE THREAD

**Issue by lesire** [AutonomyLab/ardrone_autonomy#90]
Hello guys,

Is anybody working on getting the GPS data when the GPS receiver is plugged to the drone? Is there any fork/branch I can try for that purpose?

If you have another solution (I have looked at using MAVlink / ROS bridge but the doc is clearly out-of-date), I can manage to try it and maybe find a way to merge something with this repo.

Cheers,

Charles

**Comment by mani-monaj** [comment]
The GPS receiving is not yet supported by the driver, mainly due to the fact that I do not have access to one. In addition, there is no data structure currently in `/ARDroneLib/Soft/Common/navdata_common.h` for GPS data. However other projects managed to figure out the data structure (e.g. look at [this](https://github.com/puku0x/cvdrone/blob/master/src/ardrone/ardrone.h#L719)). It should be fairly easy to manually add support for GPS to `navdata_common.h`.

**Comment by lesire** [comment]
I have the navdata_common.h and navdata_keys.h that contain the GPS-related structure (I directly asked them to Parrot).
Once I have replaced these files in the SDK, what should I do?

**Comment by lesire** [comment]
Ok, I think I got it: https://github.com/lesire/ardrone_autonomy/tree/gps
Seems to work in my office (I get the gps data; but I receive no GPS signal).
Still have to check that it's ok outdoor...

**Comment by mani-monaj** [comment]
Great. Looking forward to more news regarding this.

Did you get a complete SDK from parrot or just the required header files for GPS?

**Comment by lesire** [comment]
Le 20/02/2014 03:18, Mani Monajjemi a écrit :

> Great. Looking forward to more news regarding this.

As soon as I have something reliable, I will make a pull request.

> Did you get a complete SDK from parrot or just the required header 
> files for GPS?

Only the navdata_common and navdata_keys headers. They have not released 
a more recent version of the SDK than 2.0.1, so they won't send a 
complete "non-official" release.
